[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "traj_convert"
version = "0.9.1"
authors = [
  { name="Bastian Havers-Zulka", email="bastian.havers-zulka@ri.se" },
]
description = "Record and convert trajectories from Carla."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "polars<1.9",
    "betterosi; python_version >= '3.10'",
    "rich-argparse; python_version >= '3.10'",
]
license = {file = "LICENSE"}

[project.optional-dependencies]
carla = ["carla==0.9.15"]
omega-prime = ["omega-prime"]