[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "traj_convert"
version = "0.9.0"
authors = [
  { name="Bastian Havers-Zulka", email="bastian.havers-zulka@ri.se" },
]
description = "Record and convert trajectories."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "carla==0.9.15",
    "polars",
]
license = {file = "LICENSE"}